[pytest]
# Diretórios onde os testes estão localizados
testpaths = tests
# Padrão dos arquivos de teste
python_files = test_*.py
# Padrão dos métodos de teste
python_functions = test_*
# Coverage configuration
eval = False
addopts = --cov=src --cov-report=term-missing --cov-report=xml:coverage.xml --cov-fail-under=100
