[pytest]
minversion = 6.0
addopts = --strict-markers --doctest-glob='*.py' --cov=src --cov-report=term --cov-fail-under=100
testpaths = src tests
python_files = test_*.py
doctest_optionflags = ELLIPSIS NORMALIZE_WHITESPACE
