sonar.projectKey=adams-bashforth-3
sonar.projectName=adams-bashforth-3
sonar.projectVersion=1.0

# 1. Mapeamento exato de onde está o código e onde estão os testes
sonar.sources=src
sonar.tests=tests

# 2. Configurações de linguagem
sonar.language=py
sonar.sourceEncoding=UTF-8

# 3. Caminho do arquivo de coverage
sonar.python.coverage.reportPaths=coverage.xml

# 4. Exclusões agressivas (para ele não ler os arquivos de texto do agente ou o .venv)
sonar.exclusions=**/__pycache__/**,**/.tox/**,**/*.pyc,**/venv/**,**/.venv/**,*.txt,*.md
